# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd48fbff0de3a40fdbe6d61ef1110e4af9d3d3b3dabcd44b3cd0fce3e7fbfcd225c43abfbeecfa03fdbb2160b118298dab8086edd7f93a0530ffc3a1db1de643

test:
  secret_key_base: 9d3535c39b7ebc98869cd1fea31ef018408569e65fd67c3e99d320a2ccfddafda2ab9d78b3c472bf274c453e54f43a38bbff82fbed31eb4aa937fbefa8f29488

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
